# Generated by Django 3.1.2 on 2020-10-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_villians'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('photo_url', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
