# Generated by Django 3.1.2 on 2020-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20201021_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipeId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryId', models.IntegerField(max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('photo_url', models.CharField(max_length=120)),
                ('photosArray', models.TextField(max_length=500)),
                ('time', models.IntegerField(max_length=10)),
                ('ingredients', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Villians',
        ),
    ]
