# Generated by Django 3.1.2 on 2020-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20201021_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='categoryId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='time',
            field=models.IntegerField(),
        ),
    ]
